version: "3.8"
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ada
    networks:
      - ada-net
    volumes: 

      - db:/var/lib/postgresql/data
  backend-flask:
    environment:
      CONNECTION_URL: "postgresql://postgres:ada@db:5432/cruddur"
      BACKEND_URL: "http://localhost:4567"
      FRONTEND_URL: "http://localhost:3000"
    # env_file:
    #   - .env
    build: ./backend-flask 
    depends_on:      
      - db 
    ports:
      - "4567:4567"
    networks:
      - ada-net
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    # env_file:
    #   - .env
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
      REACT_APP_AWS_PROJECT_REGION: "us-east-1"
      REACT_APP_AWS_COGNITO_REGION: "us-east-1"
      REACT_APP_AWS_USER_POOLS_ID: "us-east-1_JtCLJk9pn"
      REACT_APP_CLIENT_ID: "oq199bt1i98d8fm471d8i32u4"
    build:
      context: ./frontend-react-js
      dockerfile: Dockerfile.prod
    depends_on:      
      - backend-flask  
    ports:
      - "3000:3000"
    networks:
      - ada-net
    volumes:
      - ./frontend-react-js:/frontend-react-js
  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - ada-net
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
networks:
  ada-net:
    driver: bridge
    name: ada-net
